# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a933ea44da5b69df2a7516e90ee842d603f914e548e901e4c5ce177c9a8342706dc7a3c8ccfb07543369430c1dd17526fc0183b4372aff21142c85be577e68f8

test:
  secret_key_base: 30b081f06541c6a12b9c2bcbcff79d258eb53b80c23fcf23eaa994e4dab179ca13dda1f57154e3dd1ea8bc9fcd8b323744ef8e979a85e4ecb0ad8e9830357773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
